"""initial migration

Revision ID: 17f062caebf6
Revises: None
Create Date: 2016-02-15 21:05:23.732936

"""

# revision identifiers, used by Alembic.
revision = '17f062caebf6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
