"""initial

Revision ID: 2c08cc6eea6a
Revises: None
Create Date: 2016-03-15 01:39:29.321000

"""

# revision identifiers, used by Alembic.
revision = '2c08cc6eea6a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameraName', sa.String(length=10), nullable=True),
    sa.Column('resolution', sa.Enum('low', 'medium', 'high'), nullable=True),
    sa.Column('vflip', sa.Boolean(), nullable=True),
    sa.Column('hflip', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cameras_cameraName', 'cameras', ['cameraName'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    op.drop_table('users')
    op.drop_index('ix_cameras_cameraName', 'cameras')
    op.drop_table('cameras')
    ### end Alembic commands ###
