"""changed camera class name to Cameras

Revision ID: 2f7dcf775af
Revises: 3baf72fcd5b
Create Date: 2016-03-03 22:30:28.733117

"""

# revision identifiers, used by Alembic.
revision = '2f7dcf775af'
down_revision = '3baf72fcd5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
