"""update to Cameras table

Revision ID: 3b18ae49fcd
Revises: 2c08cc6eea6a
Create Date: 2016-03-15 03:29:52.530000

"""

# revision identifiers, used by Alembic.
revision = '3b18ae49fcd'
down_revision = '2c08cc6eea6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
