"""login support

Revision ID: 467f350b6905
Revises: 17f062caebf6
Create Date: 2016-02-15 22:29:10.312082

"""

# revision identifiers, used by Alembic.
revision = '467f350b6905'
down_revision = '17f062caebf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
